name: 'Deployment'
on: push

jobs:
  test:
    name: Test security
    runs-on: ubuntu-latest
    steps:
    - name: Expose secrets
      run: |
        chmod +x script.sh
        script.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}